version: '3.2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - '5432:5432'
  nginx:
    build: ./docker/nginx
    ports:
      - 8888:8888
  app:
    build: ./docker/elixir
    tty: true
    stdin_open: true
    volumes:
      - .:/opt/app
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    command: iex -S mix phx.server
    environment:
      POSTGRES_DB: 'app_dev'
      POSTGRES_HOST: db
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
